version: "3"
services:
  playground-boss:
    image: gcc:latest
    container_name: playground-boss
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./:/home"

  playground-c:
    image: gcc:latest
    container_name: playground-c
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./c:/home"

  playground-cpp:
    image: gcc:latest
    container_name: playground-cpp
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./c++:/home"

  playground-java:
    image: openjdk:11
    container_name: playground-java
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./java:/home"

  playground-python:
    image: python:latest
    container_name: playground-python
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./python:/home"